# Generated by Django 4.2.1 on 2023-05-28 12:51

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='note',
            managers=[
                ('noteManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
